### ISSUE TITLE
Depricated in php5

### ISSUE THREAD

**Issue by ytiurin** [dimikot/DbSimple#1]
PHP Version 5.3.3

error_reporting(E_ALL);

output this:

Deprecated: Assigning the return value of new by reference is deprecated in Z:\home\plati\www\lib\DBSimple\DbSimple\Generic.php on line 113

Deprecated: Assigning the return value of new by reference is deprecated in Z:\home\plati\www\lib\DBSimple\DbSimple\Generic.php on line 133

Deprecated: Assigning the return value of new by reference is deprecated in Z:\home\plati\www\lib\DBSimple\DbSimple\Mysql.php on line 73

**Comment by dimikot** [comment]
Unfortunately this issue could not be fixed without broking PHP4 compatibility. But PHP4 compatibility is quite important, because a lot of old PHP4 projects use DbSimple.

You may do

error_reporting(E_ALL & ~E_STRICT);

**Comment by ivan1986** [comment]
a lot of old PHP4 projects use DbSimple ???

all projects, used php4 no updating libs long time - they not be updating DbSimple or other librares
