### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by e-oz** [dimikot/DbSimple#2]
Hello. I found only one test https://github.com/DmitryKoterov/DbSimple/blob/master/test/DbSimple/connect.php (and it cannot be called test).
Do you have any plans about unit-tests for this library?

**Comment by dimikot** [comment]
Tests (PHPT) are at https://github.com/DmitryKoterov/DbSimple/tree/master/t , not at the place you specified. They should be run using "pear run-tests -r" command-line.

**Comment by e-oz** [comment]
Oh, really. Name of directory not so obvious :) Sorry.
